title: The Molecular Biodiversity Greece Community    # Minimal theme
logo: /assets/img/MBGC-Logo.png
description: This is the website of the Molecular Biodiversity Greece Community
show_downloads: false #true
google_analytics:
theme: jekyll-theme-minimal
